version: "3.8" # Specify Docker Compose version

services:
  # vey-badminton-ws: # Your app service name
  #   build: . # Build from the Dockerfile in the current directory
  #   ports:
  #     - "3000:3000" # Expose port 3000 of the container
  #   depends_on:
  #     - mongodb
  #     - redis
  #     - elasticsearch
  #   environment:
  #     - MONGODB_URI=mongodb://mongodb:27017/vey_badminton_db # MongoDB connection string
  #     - REDIS_HOST=redis
  #     - REDIS_PORT=6379
  #     - ELASTICSEARCH_HOST=elasticsearch
  #     - ELASTICSEARCH_PORT=9200
  #   volumes:
  #     - .:/app # Mount current directory into the container

  mariadb:
    image: mariadb:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: quytp # Thay đổi mật khẩu của bạn
      MYSQL_DATABASE: vey-badminton
      MYSQL_USER: quytp
      MYSQL_PASSWORD: quytp
    ports:
      - 3306:3306
    volumes:
      - mariadb_data:/var/lib/mysql

  # mongodb:
  #   image: mongo:latest
  #   restart: always
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: quytp # Thay đổi username của bạn
  #     MONGO_INITDB_ROOT_PASSWORD: quytp # Thay đổi mật khẩu của bạn
  #   ports:
  #     - 27017:27017
  #   volumes:
  #     - mongodb_data:/data/db

  redis:
    image: redis:latest
    restart: always
    ports:
      - 6379:6379

  # elasticsearch:
  #   image: docker.elastic.co/elasticsearch/elasticsearch:7.17.11
  #   restart: always
  #   environment:
  #     - discovery.type=single-node
  #   ports:
  #     - 9200:9200
  #     - 9300:9300
  #   ulimits:
  #     memlock:
  #       soft: -1
  #       hard: -1
  #   volumes:
  #     - elasticsearch_data:/usr/share/elasticsearch/data

volumes:
  mariadb_data:
  mongodb_data:
  elasticsearch_data:
